<?php

namespace Ephp\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository {

    public function archive($table = 'blog_posts') {
        $connection = $this->getEntityManager()->getConnection();
        $q = "SELECT month, year, COUNT(*) AS n FROM {$table} GROUP BY month, year ORDER BY year DESC, month DESC";
        $stmt = $connection->executeQuery($q);
        return $stmt->fetchAll();
    }

    public function category($id, $max, $from) {
        return $this->createQueryBuilder('p')
                        ->leftJoin('p.categories', 'c')
                        ->where('c.id = :id')
                        ->setParameter('id', $id)
                        ->setMaxResults($max)
                        ->setFirstResult($from)
                        ->orderBy('p.createdAt', 'DESC')
                        ->getQuery()
                        ->execute();
    }

    public function categories($category = 'blog_categories', $join = 'blog_posts_categories') {
        $connection = $this->getEntityManager()->getConnection();
        $q = "SELECT c.name, COUNT(*) AS n FROM {$join} pc LEFT JOIN {$category} c ON c.id = pc.category_id WHERE c.show = 1 GROUP BY pc.category_id";
        $stmt = $connection->executeQuery($q);
        return $stmt->fetchAll();
    }

}
